linspace()通过指定开始值，终值和元素个数来创建表示等差数列的以为数组，可以通过endpoint参数指定是否包含终值

In [8]:
import numpy as np

In [9]:
np.linspace(0,1,10)

array([ 0.        ,  0.11111111,  0.22222222,  0.33333333,  0.44444444,
        0.55555556,  0.66666667,  0.77777778,  0.88888889,  1.        ])

步长为1/9

In [12]:
np.linspace(0,1,10,endpoint=False)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9])

步长为1/10

In [15]:
np.random.seed(42)
a = np.random.randint(0, 8, 10)#用randint()创建10个元素、值在0到9 范围之内的随机整数数组
np.unique(a)#通过unique(a)可以找到数组a中所有的整数，并按照升序排列

array([1, 2, 3, 4, 6, 7])

In [18]:
x, index = np.unique(a, return_index=True)

In [19]:
x, rindex = np.unique(a, return_inverse=True)

In [22]:
np.bincount(a)#对整数数组中各个元素所出现的次数进行统计，它要求数组中所有的元素都是非负的. 其返回数组中第 i个元素的值表示整数i出现的次数

array([0, 1, 1, 1, 3, 0, 3, 1])

* zeros()将数组初始化为0, ones()将数组初始化为1,

In [1]:
import numpy as np#创建长度为4,元素类型为整型的以为数组
np.zeros(4,np.int)

array([0, 0, 0, 0])

* full()将数组元素初始化为指定的值

In [2]:
np.full(4,np.pi)

array([ 3.14159265,  3.14159265,  3.14159265,  3.14159265])

In [3]:
def func(i):
    return i % 4 +1
np.fromfunction(func, (10,))

array([ 1.,  2.,  3.,  4.,  1.,  2.,  3.,  4.,  1.,  2.])

* fromfunction()的第一个参数是计算每个数组元素的函数, 第二个参数指定数组的形状. 因为它支持多维数组, 所以第二个参数必须是一个序列.

In [4]:
def func2(i, j):
    return (i + 1)*(j + 1)
np.fromfunction(func2, (9,9))#输出数组a中的每个元素a[i,j]都等于func2(i,j)

array([[  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.],
       [  2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.],
       [  3.,   6.,   9.,  12.,  15.,  18.,  21.,  24.,  27.],
       [  4.,   8.,  12.,  16.,  20.,  24.,  28.,  32.,  36.],
       [  5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.],
       [  6.,  12.,  18.,  24.,  30.,  36.,  42.,  48.,  54.],
       [  7.,  14.,  21.,  28.,  35.,  42.,  49.,  56.,  63.],
       [  8.,  16.,  24.,  32.,  40.,  48.,  56.,  64.,  72.],
       [  9.,  18.,  27.,  36.,  45.,  54.,  63.,  72.,  81.]])

In [8]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
a[5]

5

In [10]:
a[3:5]

array([3, 4])

In [11]:
a[:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [12]:
a[1:-1:2]#切片中第三个参数表示步长，2表示隔一个元素取一个元素

array([1, 3, 5, 7])

In [13]:
a[5:1:-2]#步长为负数时,开始下标必须大于结束下标

array([5, 3])

* 下标还可以修改元素的值

#### 多维数组

In [15]:
a = np.arange(0,60,10).reshape(-1,1)+np.arange(0,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

多维数组的存取和一维数组类似, 因为多维数组有多个轴, 所以它的下标需要多个值来表示.Numpy采用元组作为数组的下标, 元组中的每个元素和数组的每个周对应

In [ ]:
import numpy as np 
number = np.linspace(0.1, 10, 100)#1
y = number.astype(np.float32)
x2 = y*0.5
i = y.view(np.int32)#2
i[:] = 0x5f3759df - (i >> 1)#3
y = y * (1.5 - x2 * y * y)#4
np.max(np.abs(1 / np.sqrt(number) - y))#5

1. 由于linspace()创建的数组类型为双精度浮点数, 因此这里首先通过astype()方法将其转换为单精度浮点数数组y;
2. 通过view()的方法创建一个与y共享内存的32位整数数组i;
3. 
4. 进行一次牛顿迭代计算
5. 最后输出真实值和近似值之间的最大误差

In [ ]:
a = np.arange(0, 60, 10).reshape(-1, 1)
b = np.arange(0,5)
b.shape = 1,5#补齐为(1,5)
b
c = a + b
c

a与b的维数不同, 会进行广播，就需进行广播处理:需要让b的shape属性向a看齐,于是在b 
的shape属性前加1,补齐为(1,5);输出数组的各个轴的长度为输入数组各个轴的长度的
最大值，可知输出数组的shape属性为(6,5)
由于

In [36]:
b = np.arange(0, 5).reshape(1,5)
b = b.repeat(6, axis = 0)#repeat()是指沿着axis参数指定的轴复制数组中各个元素的值
b

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])