linspace()通过指定开始值，终值和元素个数来创建表示等差数列的以为数组，可以通过endpoint参数指定是否包含终值

In [8]:
import numpy as np

In [9]:
np.linspace(0,1,10)

array([ 0.        ,  0.11111111,  0.22222222,  0.33333333,  0.44444444,
        0.55555556,  0.66666667,  0.77777778,  0.88888889,  1.        ])

步长为1/9

In [12]:
np.linspace(0,1,10,endpoint=False)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9])

步长为1/10

In [15]:
np.random.seed(42)
a = np.random.randint(0, 8, 10)#用randint()创建10个元素、值在0到9 范围之内的随机整数数组
np.unique(a)#通过unique(a)可以找到数组a中所有的整数，并按照升序排列

array([1, 2, 3, 4, 6, 7])

In [18]:
x, index = np.unique(a, return_index=True)

In [19]:
x, rindex = np.unique(a, return_inverse=True)

In [22]:
np.bincount(a)#对整数数组中各个元素所出现的次数进行统计，它要求数组中所有的元素都是非负的. 其返回数组中第 i个元素的值表示整数i出现的次数

array([0, 1, 1, 1, 3, 0, 3, 1])